DROP TABLE IF EXISTS AGGRESIVE_DRIVING;
CREATE TABLE AGGRESIVE_DRIVING(
GENDER TEXT,
PERCENT_OF_AGGRESSIVE_DRIVING_INCIDENTS FLOAT);
INSERT INTO AGGRESIVE_DRIVING(GENDER, PERCENT_OF_AGGRESSIVE_DRIVING_INCIDENTS)
SELECT
PERSON_SEX,
ROUND((SUM(CASE WHEN PRIMARY_CONTRIBUTING_FACTOR = 'Aggressive Driving/Road Rage' THEN 1 ELSE 0 END) * 100.0) / 
(SELECT COUNT(*) FROM ny_col_merge2 WHERE PRIMARY_CONTRIBUTING_FACTOR = 'Aggressive Driving/Road Rage'),2) AS PERCENT_OF_AGGRESSIVE_DRIVING_INCIDENTS
FROM ny_col_merge2
GROUP BY PERSON_SEX;
